###############################################################################
# Step 1 : Builder image
#
FROM golang:1.17.6-alpine3.15 AS builder

ENV GO111MODULE=on
ENV GOOS=linux
ENV GOARCH=amd64
#ENV CGO_ENABLED=1

#Install dependencies
RUN apk --no-cache add ghostscript 

WORKDIR /app

RUN addgroup -g 1001 -S app
RUN adduser -S app -u 1001
RUN chmod -R 700 /app

USER app

EXPOSE 3000