version: "3"

services:
  gotenberg:
    image: gotenberg/gotenberg:7.5.4
    # Custom base root
    command: "gotenberg --api-root-path=/pdf-gotenberg/ --api-timeout=600s --unoconv-disable-listener=true"
    shm_size: "4gb"
    restart: always
    logging:
      options:
        max-size: "512m"
        max-file: "7"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - API_ROOT=/pdf-gotenberg
    ports:
      - "3000:3000"
    logging:
      options:
        max-size: "512m"
        max-file: "7"